version: "3"

services:
    searcher-redis:
        container_name: searcher-redis
        image: "redis:alpine"
        command: redis-server --maxmemory 20M --maxmemory-policy volatile-lru
        ports:
            - "6379:6379"

    searcher:
        container_name: searcher
        env_file: .env
        build:
            dockerfile: Dockerfile
            context: ./searcher
        ports:
            - "5000:5000"
